steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'my-app/pom.xml' # Correct path based on your repo image
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    # CHANGE THIS FROM 1.11 TO 1.17
    jdkVersionOption: '1.17' 
    jdkArchitectureOption: 'x64'
    mavenOptions: '-Xmx3072m'
